# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutomatizacionGmail():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_automatizacionGmail(self):
    self.driver.get("https://accounts.google.com/AccountChooser/signinchooser?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&flowName=GlifWebSignIn&flowEntry=AccountChooser")
    self.driver.set_window_size(814, 852)
    self.driver.find_element(By.CSS_SELECTOR, ".BHzsHc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".FliLIb > .VfPpkd-vQzf8d").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-ksKsZd-mWPk3d > .VfPpkd-StrnGf-rymPhb-b9t22c").click()
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("juan")
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("pesos")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("juanpesos")
    self.driver.find_element(By.ID, "username").send_keys("juanpesos123")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("juanpesos12")
    self.driver.find_element(By.CSS_SELECTOR, ".oMzjQd:nth-child(1) > .fBRZbb").click()
    self.driver.find_element(By.NAME, "Passwd").click()
    self.driver.find_element(By.NAME, "Passwd").send_keys("A12345SD")
    self.driver.find_element(By.NAME, "ConfirmPasswd").click()
    self.driver.find_element(By.NAME, "ConfirmPasswd").send_keys("A12345SD")
    self.driver.find_element(By.CSS_SELECTOR, ".sSzDje").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sSzDje").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-muHVFf-bMcfAe").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
    self.driver.find_element(By.ID, "day").click()
    self.driver.find_element(By.NAME, "recoveryEmail").click()
    self.driver.find_element(By.NAME, "recoveryEmail").send_keys("eldemoledor1620@gmail.com")
    self.driver.find_element(By.ID, "day").click()
    self.driver.find_element(By.ID, "day").send_keys("20")
    self.driver.find_element(By.ID, "month").click()
    dropdown = self.driver.find_element(By.ID, "month")
    dropdown.find_element(By.XPATH, "//option[. = 'Abril']").click()
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys("1994")
    self.driver.find_element(By.ID, "gender").click()
    dropdown = self.driver.find_element(By.ID, "gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Hombre']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
    element = self.driver.find_element(By.LINK_TEXT, "Términos")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
